### ISSUE TITLE
视频可以正常观看，但是列表页上方有报错提示，如图

### ISSUE THREAD

**Issue by xynu617** [scjtqs/91porn#11]
![Ubuntu1804 64 位-2020-02-15-21-57-11](https://user-images.githubusercontent.com/53331950/74589626-c798d600-5041-11ea-962c-2f810d4a80f7.jpg)

用的lnmp.org的LNMP一键安装包 V1.6 ，PHP版本7.1.33，系统是Ubuntu18.04

**Comment by scjtqs** [comment]
嗯，按理来说这个是你本地环境的配置引起的，但是鉴于很多人不会搞本地配置的修改，我干脆在代码中直接屏蔽掉了错误信息。更新一下代码可以解决问题

**Comment by scjtqs** [comment]
其实吧，你上面的错误提示代表着 你的配置环境是有问题的。你的php的环境权限有问题，建议你对你的代码文件进行chmod -R 777 /yourPath/91porn 处理

**Comment by xynu617** [comment]
> 其实吧，你上面的错误提示代表着 你的配置环境是有问题的。你的php的环境权限有问题，建议你对你的代码文件进行chmod -R 777 /yourPath/91porn 处理

谢谢！
