### ISSUE TITLE
大佬更新一下代码吧，91加密改了，解析失败了

### ISSUE THREAD

**Issue by lang999** [scjtqs/91porn#16]

**Comment by scjtqs** [comment]
好了，修复了~！

**Comment by yuccacl** [comment]
非常谢谢~~
我自己按照如下方法修改了一下，也可以工作，供参考：

把 $video=$xpath->query('//[@id="player_one"]/source')->item(0);//video
改成 $video=$xpath->query('//[@id="player_one"]/*')->item(0);//video

$html = getHtml($url);
$dom = new \DOMDocument();
//从一个字符串加载HTML
@$dom->loadHTML($html);
//使该HTML规范化
$dom->normalize();
//用DOMXpath加载DOM，用于查询
$xpath = new \DOMXPath($dom);
$title=$xpath->query('//[@id="viewvideo-title"]')->item(0)->textContent;
$video=$xpath->query('//[@id="player_one"]/*')->item(0);//video
$video=$video->ownerDocument->saveHTML($video);
