### ISSUE TITLE
用gearhost搭建但是进set提示这个

### ISSUE THREAD

**Issue by villainousx** [scjtqs/91porn#17]
`Warning: require_once(ROOT\lib/phpQuery.php): failed to open stream: No such file or directory in C:\home\site\wwwroot\functions.php on line 8 Fatal error: require_once(): Failed opening required 'ROOT\lib/phpQuery.php' (include_path='.;C:\php\pear') in C:\home\site\wwwroot\functions.php on line 8`

请问这个是怎么回事呀

**Comment by scjtqs** [comment]
修复了下对win服务器的支持。请git pull

**Comment by villainousx** [comment]
不是win 就是那种虚拟主机

**Comment by scjtqs** [comment]
你的虚拟主机应该是部署在win系统的，只有win才会出现c盘这个盘符。你用最新代码试试吧

**Comment by villainousx** [comment]
现在在index里会提示这个Warning: Invalid argument supplied for foreach() in C:\home\site\wwwroot\291\index.php on line 97

换成旧网址也无效

**Comment by scjtqs** [comment]
亲，你需要翻墙



---原始邮件---
发件人: "villainousx"<notifications@github.com&gt;
发送时间: 2020年4月13日(周一) 中午12:22
收件人: "scjtqs/91porn"<91porn@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"scjtqs"<scjtqs@qq.com&gt;;
主题: Re: [scjtqs/91porn] 用gearhost搭建但是进set提示这个 (#17)




 
现在在index里会提示这个Warning: Invalid argument supplied for foreach() in C:\home\site\wwwroot\291\index.php on line 97
 
换成旧网址也无效
