### ISSUE TITLE
小白一枚，烦请大佬指点

### ISSUE THREAD

**Issue by dxs1256** [scjtqs/91porn#18]
使用宝塔面板安装。打开网站就这样。小白一枚，烦请大佬指点
![FireShot Capture 004 - 视频列表-91视频预览 - 91 orrz ml](https://user-images.githubusercontent.com/23136671/79040191-53ca1280-7c19-11ea-9ec0-8516270b81da.png)

**Comment by villainousx** [comment]
我也是这样…

**Comment by yuccacl** [comment]
91改版了，把里面的域名换成旧版域名就可以解决问题

**Comment by dxs1256** [comment]
> 91改版了，把里面的域名换成旧版域名就可以解决问题

还是没有明白。服务器在国外，已经把set.php里91地址改为91porn.com还是不行

**Comment by yuccacl** [comment]
> > 91改版了，把里面的域名换成旧版域名就可以解决问题
> 
> 
> 
> 还是没有明白。服务器在国外，已经把set.php里91地址改为91porn.com还是不行

不要用这个地址，去官网找旧版地址

**Comment by dxs1256** [comment]
> 我也是这样...请问解决了吗

根据大佬提示把set.php和index.php里的http://91porn.com全部换成http://old.workgreat11.live就欧克了

**Comment by villainousx** [comment]
我还是不行..用另一个项目这样的源码又可以了 但是没有分类

**Comment by scjtqs** [comment]
已修改最新域名版本适配

**Comment by villainousx** [comment]
> 已修改最新域名版本适配

是不报错了 但是不管用不用梯子都是空白的 包括样例地址进去也是空白的 修改了域名也一样 这个怎么解决呀

**Comment by yuccacl** [comment]
> > 已修改最新域名版本适配
> 
> 是不报错了 但是不管用不用梯子都是空白的 包括样例地址进去也是空白的 修改了域名也一样 这个怎么解决呀

你提问提供这么点信息，让别人怎么帮你解决啊
