### ISSUE TITLE
部署网站报错phpquery缺失，如何安装

### ISSUE THREAD

**Issue by luul11** [scjtqs/91porn#5]
兄弟聊一下，我正好有个香港云服务器就想部署一下，结果报错phpquery缺失，我下载了一个放到
phpquery文件夹放到www/server/php/72/lib/php还是无法解决，咨询一下，我php不太懂，谢谢

Warning: require_once(lib/phpQuery.php): failed to open stream: No such file or directory in /www/wwwroot/www.pyman.xyz/functions.php on line 4

Fatal error: require_once(): Failed opening required 'lib/phpQuery.php' (include_path='.:/www/server/php/72/lib/php') in /www/wwwroot/www.pyman.xyz/functions.php on line 4

**Comment by scjtqs** [comment]
看其实，是你的php的本地环境有问题啊。既然你的网站根目录是“/www/wwwroot/www.pyman.xyz/”，为何在执行过程中的根目录却变成了“/www/server/php/72/lib/php”呢。。。。说一下你的机器环境是怎么配的吧，lnmp一键包还是yum install xxx 或者 apt-get xxx。如果实在不知道怎么改，我这边可以添加一些参数修正

**Comment by scjtqs** [comment]
你git pull更新一下代码再试试

**Comment by luul11** [comment]
谢谢老哥，部署成功了
