### ISSUE TITLE
被ban ip了怎么办

### ISSUE THREAD

**Issue by btssbt** [scjtqs/91porn#7]
video页面错误。
应该是被banip了
有解决方法吗

**Comment by scjtqs** [comment]
不是Ip被ban了，应该是91的cdn/dns的提供方加了强验证导致的。你可以清空所有cookie然后直接访问91的原始网站，会弹一个谷歌的人体验证

**Comment by scjtqs** [comment]
现在差不多已经好了。那段时间91的cdn服务商抽风了
