### ISSUE TITLE
video页面提示这种错误，

### ISSUE THREAD

**Issue by lx570lx580** [scjtqs/91porn#8]
Fatal error: Uncaught Error: Call to a member function saveHTML() on null in /www/91/functions.php:91 Stack trace: #0 /www/91/video.php(23): getVideo('http://www.91po...') #1 {main} thrown in /www/91/functions.php on line 91
不知道怎么解决，今天30号才发现的，不知道您有遇到这个问题吗？谢谢

**Comment by lunix769** [comment]
同问

**Comment by scjtqs** [comment]
解决了，是91网站更改了html布局，导致我这边的采集失败了，已同步更新修复
